### ISSUE TITLE
ERROR: Executables created by c compiler arm-linux-musleabi-gcc are not runnable

### ISSUE THREAD

**Issue by LatiniDav** [HexHive/SURGEON#1]

**Comment by Naardus** [comment]
I'm having a very similar Error while trying to "make run", did you manage to resolve the error code? if so could you explain how to fix it?

**Comment by LatiniDav** [comment]
I encountered this issue while running my VirtualBox v6.1 VM. I resolved it by switching to a VMware VM instead.
